### ISSUE TITLE
RuntimeError: DataLoader worker (pid(s) 1995171, 1996371) exited unexpectedly 

### ISSUE THREAD

**Issue by zeng-lingyun** [Sense-X/X-Temporal#12]
when i set workers>0, i would get error: “RuntimeError: DataLoader worker (pid(s) 1995171, 1996371) exited unexpectedly ”

It seems to happen at “batch = next(iterator)” in “.../X-Temporal/x_temporal/interface/temporal_helper.py"
（note：running the experiment “tin”）

**Comment by deepcs233** [comment]
If you only set workers=0, can it run as expected? Maybe you can check your dataset config (image_prefix, meta_file ...) in the **config.yaml** , and make sure it can find your training data correctly.

**Comment by zeng-lingyun** [comment]
> If you only set workers=0, can it run as expected? Maybe you can check your dataset config (image_prefix, meta_file ...) in the **config.yaml** , and make sure it can find your training data correctly.

Yes, it can run with workers=0.  Something wrong in my dataloader, I have solved it. 

**Thanks for your timely response！:)**
