### ISSUE TITLE
Abort the multi-label 

### ISSUE THREAD

**Issue by simobupt** [Sense-X/X-Temporal#13]
Hi. When I test, I can not find the output file and I don't find how to output the multi-label. When multi-label, how to define my pred labels are right. Thanks.

**Comment by deepcs233** [comment]
You can define your gt multi-label like [this](https://github.com/Sense-X/X-Temporal#about-multi-label-classification). The log file will be in your exp dir which looks like log.train.*** or  log.test.*** if you run the code as the way in readme.

**Comment by simobupt** [comment]
> You can define your gt multi-label like [this](https://github.com/Sense-X/X-Temporal#about-multi-label-classification). The log file will be in your exp dir which looks like log.train.*** or log.test.*** if you run the code as the way in readme.

I get my log file, however, after testing, I don't find my output file. You mean this? When multi-label, how you set your threshold to get the true label? Thanks. 

> tensor([[-16.4232,  13.8030, -17.7465,  -8.4778, -12.2690,  -6.4211, -10.1446,
         -10.7173, -18.9637, -16.3393],
        [-17.2387,  14.4860, -18.6262,  -8.8768, -12.9265,  -6.6981, -10.4857,
         -11.1755, -19.9906, -17.1772],
        [-17.8470,  14.9714, -19.3139,  -9.2063, -13.4063,  -6.8954, -10.8004,
         -11.5017, -20.7062, -17.8251],
        [-17.8988,  15.0112, -19.3701,  -9.2328, -13.4491,  -6.9146, -10.8270,
         -11.5318, -20.7675, -17.8806],
        [-16.4080,  13.7989, -17.7305,  -8.4718, -12.2654,  -6.4196, -10.1315,
         -10.7031, -18.9458, -16.3345],
        [-16.4051,  13.7975, -17.7276,  -8.4651, -12.2609,  -6.4138, -10.1311,
         -10.7010, -18.9413, -16.3300]], device='cuda:0')
2020-09-05 12:39:31,338-temporal_helper.py#429:Test: [0/2]	Time 3.135 (3.135)
tensor([[-16.3986,  13.7837, -17.7263,  -8.4589, -12.2476,  -6.4185, -10.1290,
         -10.7015, -18.9352, -16.3089],
        [-18.1527,  15.2382, -19.6569,  -9.3546, -13.6706,  -6.9802, -11.0059,
         -11.7343, -21.0639, -18.1724],
        [-17.4185,  14.6345, -18.8336,  -8.9639, -13.0505,  -6.7091, -10.6203,
         -11.3015, -20.1347, -17.3628],
        [-19.8432,  16.5801, -21.5381, -10.2100, -15.0140,  -7.5558, -11.8861,
         -12.7359, -23.0970, -19.9284],
        [-19.2284,  16.0839, -20.8627,  -9.9008, -14.5358,  -7.3400, -11.5665,
         -12.3737, -22.3715, -19.2801],
        [-18.4896,  15.4994, -20.0523,  -9.5344, -13.9326,  -7.0929, -11.1961,
         -11.9459, -21.4432, -18.5001]], device='cuda:0')
2020-09-05 12:39:33,718-temporal_helper.py#445: * mAP 100.000	Loss 0.000	total_num=12.0

**Comment by deepcs233** [comment]
Yes, the output file is that. Instead of setting threshold to get true label,  we use mAP as a metric.
About mAP, you can refer to [it](https://medium.com/@jonathan_hui/map-mean-average-precision-for-object-detection-45c121a31173).

**Comment by simobupt** [comment]
> Yes, the output file is that. Instead of setting threshold to get true label, we use mAP as a metric.
> About mAP, you can refer to [it](https://medium.com/@jonathan_hui/map-mean-average-precision-for-object-detection-45c121a31173).

Ok. Thanks. But if you modify the code instead of only using the mAP, it would be better.
