### ISSUE TITLE
About the model result

### ISSUE THREAD

**Issue by wwnbbd** [Sense-X/X-Temporal#15]
The previous issue was closed. https://github.com/Sense-X/X-Temporal/issues/14#issue-701641334 

Following your suggestion, I used multi-crops and a bigger input, I still can not reproduce the result on Multi-moments in time using TIN and slowfast model(TIN:57 vs 62 in report). However, I can get a little bit better result using tsn model(59.7 vs 58.9). Do you have any idea to solve this?

**Comment by deepcs233** [comment]
Try dropout = 0.5 ?

**Comment by wwnbbd** [comment]
I tried 0.5.....no change on the result....

**Comment by wwnbbd** [comment]
Should I retrain the model using your checkpoint for several epochs?

**Comment by wwnbbd** [comment]
I retrained the 8 frame tin model using the parameters provided, I got 61.8 with single test crop. 😂
