### ISSUE TITLE
`AverageMeter` is not correct

### ISSUE THREAD

**Issue by CarolineCheng233** [Sense-X/X-Temporal#19]
I encountered an issue similar to [this](https://github.com/deepcs233/TIN/issues/4#issue-671870771) that `AverageMeter` in [utils.py](https://github.com/Sense-X/X-Temporal/blob/master/x_temporal/utils/utils.py#L51-L81) which is used in [temporal_helper.py](https://github.com/Sense-X/X-Temporal/blob/master/x_temporal/interface/temporal_helper.py#L20) is not correct.

Could you please fix it?

**Comment by deepcs233** [comment]
I have sloved the [issue](https://github.com/deepcs233/TIN/issues/4#issue-671870771). But I think this repo may not exist this problem, you can see [here](https://github.com/Sense-X/X-Temporal/blob/8989ad99593c1b1b6f414c3488d18c8f77aecaa8/x_temporal/interface/temporal_helper.py#L418).
