### ISSUE TITLE
When training，the log file stop at 'save_dir: checkpoint/' and with no update again

### ISSUE THREAD

**Issue by SceneRec** [Sense-X/X-Temporal#20]
Thank you for your nice code. 
When I set the value in default.yaml
gpus:4
dataset: 
      **img_prefix: '{:05d}.jpg'**
      video_source :True    #because I use video as input data
      modality: Flow
train:
   meta_file : /my_path/train_videofolder.txt
 trainer: 
       **no_partial_bn: True**

I set train script: train.sh
`T=`date +%m%d%H%M`
ROOT=../..
cfg=default.yaml
export PYTHONPATH=$ROOT:$PYTHONPATH 
CUDA_VISIBLE_DEVICES=4,5,6,7 python $ROOT/x_temporal/train.py --config $cfg | tee log.train.$T`

When I run train.sh , the log file stop at 'save_dir: checkpoint/' and with no update again.
Would you kindly let me know of the problem. Thanks a lot

**Comment by deepcs233** [comment]
You can refer to [Issue 1](https://github.com/Sense-X/X-Temporal/issues/1)， check your **root**, ** meta_file** and make sure the program can find the video with the above settings. #1
