### ISSUE TITLE
Found Two fresh BUGs and a Solution

### ISSUE THREAD

**Issue by SceneRec** [Sense-X/X-Temporal#21]
Thank you for your beautiful code.
I run this model base on Kinetics dataset, and video format is .mp4. 
 1st ERROR: `RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.`
reason: Training on multiple GUPs is called tensor, which is divided into different kinds of memory or video memory.
Solution: In /.. /utils.py line 42, should add ** contiguous().view(1,-1) **, the same as line 46.

The train work but when the Iteration=40, it got a ERROR. 
2nd ERROR: `decord._ffi.base.DECORDError: [14:51:44] /io/decord/src/video/video_reader.cc:125: Check failed: st_nb >= 0 (-1381258232 vs. 0) ERROR cannot find video stream with wanted index: -1`
And `UserWarning: resource_tracker: There appear to be 122 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '`
Although I tried many ways, I still couldn't solve the problem.

Would you kindly let me know of the problem. Thanks a lot

**Comment by deepcs233** [comment]
Thank for your feedback:
For 1st ERROR, i will fix the bug.
For 2nd ERROR, you may update the version of decord and check the video path is correct and check if the video is damaged.
