### ISSUE TITLE
evaluate on test dataset when training?

### ISSUE THREAD

**Issue by HC-2016** [Sense-X/X-Temporal#4]
https://github.com/Sense-X/X-Temporal/blob/5faa5f43836f4a6e2a3296ca2ebd064bb61f42cb/x_temporal/interface/temporal_helper.py#L386

Here the data_loaders is set to "test" at any time.
I'm not sure wether this is a bug or not. Maybe there is something I misunderstand?

**Comment by deepcs233** [comment]
It may be a bug, I will update the code later. You can easily modify the code if you need to change it now.

**Comment by HC-2016** [comment]
maybe we should set **test_mode=test_mode** here:
https://github.com/Sense-X/X-Temporal/blob/master/x_temporal/utils/dataset_helper.py#L27

**Comment by deepcs233** [comment]
The arg **test_mode** in the lastest version didn't affect the training or testing, we will update the code to fix this problem.
Thanks for your suggestions

**Comment by HC-2016** [comment]
Is there any difference between _get_val_indices() and _get_test_indices()?
https://github.com/Sense-X/X-Temporal/blob/master/x_temporal/core/dataset.py#L173

**Comment by deepcs233** [comment]
In this version, they have no difference.

**Comment by HC-2016** [comment]
https://github.com/Sense-X/X-Temporal/blob/master/x_temporal/core/dataset.py#L220
https://github.com/Sense-X/X-Temporal/blob/master/x_temporal/core/dataset.py#L313

Here we count image frames from 1 and count video from 0. This difference would lead to "index out of bounds" error.
We should change "seg_ind" to "seg_ind - 1"  for video_source in https://github.com/Sense-X/X-Temporal/blob/master/x_temporal/core/dataset.py#L313.

**Comment by deepcs233** [comment]
Thanks for your suggestion, I have fixed this bug.
